auth:
    email-password: clxandlx123456
    email-smtp-host: smtp.gmail.com
    email-smtp-port: 25
    email-username: qdmzhost
    enable-email: true
    enable-oauth2: true
    enable-public-registration: true
    enable-qq: true
    enable-telegram: true
    qq-app-id: dsfdsf
    qq-app-key: dsfdsfdsf
    telegram-bot-token: dsfdsfdsf
captcha:
    enabled: true
    expire-time: 300
    height: 40
    length: 4
    width: 120
cdn:
    base-endpoint: https://cdn.spiritlhl.net/
    endpoints:
        - https://cdn0.spiritlhl.top/
        - http://cdn3.spiritlhl.net/
        - http://cdn1.spiritlhl.net/
        - http://cdn2.spiritlhl.net/
cors:
    mode: ""
    whitelist: []
invite-code:
    enabled: true
    required: false
jwt:
    buffer-time: 1d
    expires-time: 7d
    issuer: oneclickvirt
    signing-key: ""
mysql:
    auto-create: "true"
    config: charset=utf8mb4&parseTime=True&loc=Local
    db-name: oneclickvirt
    engine: InnoDB
    log-mode: error
    log-zap: "false"
    max-idle-conns: "10"
    max-lifetime: "3600"
    max-open-conns: "100"
    password: ""
    path: 127.0.0.1
    port: "3306"
    prefix: ""
    singular: "false"
    username: root
quota:
    instance-type-permissions:
        min-level-for-container: 1
        min-level-for-delete-container: 1
        min-level-for-delete-vm: 1
        min-level-for-reset-container: 1
        min-level-for-reset-vm: 1
        min-level-for-vm: 1
    level-limits:
        "1":
            max-instances: 1
            max-resources:
                bandwidth: 2
                cpu: 1
                disk: 512
                memory: 128
            max-traffic: 1024
        "2":
            max-instances: 2
            max-resources:
                bandwidth: 200
                cpu: 2
                disk: 2048
                memory: 1024
            max-traffic: 204800
        "3":
            max-instances: 3
            max-resources:
                bandwidth: 300
                cpu: 3
                disk: 3072
                memory: 1536
            max-traffic: 307200
        "4":
            max-instances: 4
            max-resources:
                bandwidth: 400
                cpu: 4
                disk: 4096
                memory: 4096
            max-traffic: 409600
        "5":
            max-instances: 5
            max-resources:
                bandwidth: 500
                cpu: 5
                disk: 5120
                memory: 5120
            max-traffic: 512000
    default-level: 1
redis:
    addr: ""
    db: 0
    password: ""
system:
    addr: 8890
    db-type: mysql
    env: development
    frontend-url: "http://154.12.84.134"
    iplimit-count: 15000
    iplimit-time: 3600
    oauth2-state-token-minutes: 15
    oss-type: local
    provider-inactive-hours: 24
    use-multipoint: false
    use-redis: false
task:
    delete-retry-count: 3
    delete-retry-delay: 2
upload:
    max-avatar-size: 2
other:
    default-language: zh-CN
    max-avatar-size: 2
zap:
    director: storage/logs
    encode-level: LowercaseLevelEncoder
    format: console
    level: info
    log-in-console: true
    max-array-elements: 5
    max-backups: 15
    max-file-size: 5
    max-log-length: 2000
    max-string-length: 1000
    prefix: '[oneclickvirt]'
    retention-day: 3
    show-line: false
    stacktrace-key: stacktrace
max_avatar_size: 2
default_language:
signing_key_v1:
    created_at: "2025-12-30T15:38:24.4622672+08:00"
    expires_at: "2025-12-31T15:38:24.4622672+08:00"
    is_active: false
    key: 3d60046ddbb61b7cfe6e400eafdd4baf493f34e35ab728b70c96a5c0bdeeb75a
    version: 1
active_version: 1
payment:
    alipay-app-id: "323232"
    alipay-gateway: https://openapi.alipay.com/gateway.do
    alipay-private-key: 23232323ewdsdsaddsadsd
    alipay-public-key: "342323232"
    balance-daily-limit: 9998
    balance-min-amount: 2
    enable-alipay: true
    enable-balance: true
    enable-wechat: true
    wechat-api-key: "34343"
    wechat-api-v3-key: "34343"
    wechat-app-id: "34343"
    wechat-mch-id: "434343"
    wechat-serial-no: "343434"
    wechat-type: mp
